steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops-dev','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops-dev"]
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops-dev
  - --location=southamerica-west1-b
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-dev
