apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  labels:
    app: gcp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/second-hold-388702/gcpdevops-dev:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: gcp-devops-dev
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  type: LoadBalancer
  selector:
    app: gcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
